### ISSUE TITLE
Javascript fundamental concept

### ISSUE THREAD

**Issue by sukrosono** [benoror/ama#1]
Hi i just wondering would you suggest me some javascript concept which i have to know?
I just learn C++ first then java, php and now focusing on js. i read some book,watch video tutorial but many of them just cover DOM manipulation and ajax call, i really afraid if i have miss something important. Since i jump directly to angular js, and lead many problem. Last things i read is javascript `closure`, maybe you want help newcomers :smile_cat:

**Comment by benoror** [comment]
Hey @brutalcrozt,

I would suggest to learn vanilla JavaScript fundamentals very well. Objects, prototypes, closures, variable hoisting, scopes, execution contexts, etc.

Here are some links to get started:
- https://toddmotto.com/
  - https://toddmotto.com/understanding-the-this-keyword-in-javascript/
  - https://toddmotto.com/everything-you-wanted-to-know-about-javascript-scope/
- https://medium.com/javascript-scene
  - https://medium.com/javascript-scene/learn-javascript-b631a4af11f2#.m2kw1pubm
  - https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3#.elohjl7vn
  - https://medium.com/javascript-scene/the-two-pillars-of-javascript-pt-2-functional-programming-a63aa53a41a4#.t9t315oxa
  - https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-closure-b2f0d2152b36#.8mkp0cyl3

I have a Twitter list with interesting people related to JavaScript:
- https://twitter.com/benoror/lists/javascript

Regarding angular you can learn a lot from screencasts at [egghead.io](http://egghead.io) (some made by @kentcdodds btw :smile:)

Cheers!
