### ISSUE TITLE
(how to test dependencies which resolve via ui-router.resolve)dude help

### ISSUE THREAD

**Issue by sukrosono** [benoror/ama#2]
Hey man i decide to write unit test, but it's failing.
i don't even write anything real now. 
i have 4 dependency solved via `ui.router.resolve` and now i write test for controller.
i really stuck and stackoverflow doesn't help much.

**Comment by benoror** [comment]
Can you isolate the issue in a http://jsbin.com/?html,css,js,output ?

**Comment by sukrosono** [comment]
Thanks anyway. Lately i think it can be achieve via unit testing :confused:
